<?php
/**
 * Created by PhpStorm.
 * User: saiya
 * Date: 4/29/18
 * Time: 1:05 PM
 */

namespace AppBundle\Repository;


use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository {

    public function findLastThreeArticles() {
        $qb = $this->_em->createQueryBuilder();

        $qb->select('a')
            ->from('AppBundle:Article', 'a')
            ->orderBy('a.datePublished', 'DESC')
            ->setMaxResults(3);

        return $qb->getQuery()->getResult();
    }

    public function findAllArticlesByDateDesc() {
        $qb = $this->_em->createQueryBuilder();

        $qb->select('a')
            ->from('AppBundle:Article', 'a')
            ->orderBy('a.datePublished', 'DESC');

        return $qb->getQuery()->getResult();
    }

    public function findMostViewedArticles() {
        $qb = $this->_em->createQueryBuilder();

        $qb->select('a')
            ->from('AppBundle:Article', 'a')
            ->orderBy('a.views', 'DESC')
            ->setMaxResults(4);

        return $qb->getQuery()->getResult();
    }

    public function findLastFourArticles() {
        $qb = $this->_em->createQueryBuilder();

        $qb->select('a')
            ->from('AppBundle:Article', 'a')
            ->orderBy('a.datePublished', 'DESC')
            ->setMaxResults(4);

        return $qb->getQuery()->getResult();
    }
}