<?php
/**
 * Created by PhpStorm.
 * User: saiya
 * Date: 11/04/18
 * Time: 15:05
 */

namespace AppBundle\Repository;


use Doctrine\ORM\EntityRepository;

/**
 * DossierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DossierRepository extends EntityRepository {

    public function findAllActivatedDossiers() {
        $qb = $this->_em->createQueryBuilder();

        $qb->select('d')
            ->from('AppBundle:Dossier', 'd')
            ->where('d.enabled = 1')
            ->orWhere('d.enabled = 2');

        return $qb->getQuery()->getResult();
    }
}