<?php
/**
 * Created by PhpStorm.
 * User: saiya
 * Date: 11/04/18
 * Time: 15:05
 */

namespace AppBundle\Repository;


use Doctrine\ORM\EntityRepository;

/**
 * GlobalParametersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GlobalParametersRepository extends EntityRepository {

}