<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * GroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupRepository extends EntityRepository {
    public function findGroupByAge(User $user) {
        $qb = $this->_em->createQueryBuilder();

        $qb->select('g')
            ->from('AppBundle:Group', 'g')
            ->where(':age BETWEEN g.minAge AND g.maxAge')
            ->setParameter(':age', $user->getAge());

        return $qb->getQuery()->getOneOrNullResult();
    }
}
