<?php
/**
 * Created by PhpStorm.
 * User: saiya
 * Date: 4/29/18
 * Time: 1:05 PM
 */

namespace AppBundle\Repository;


use Doctrine\ORM\EntityRepository;

/**
 * TrainingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrainingRepository extends EntityRepository {

    public function findLastTenArticles() {
        $qb = $this->_em->createQueryBuilder();

        $qb->select('t')
            ->from('AppBundle:Training', 't')
            ->orderBy('t.id', 'DESC')
            ->setMaxResults(10);

        return $qb->getQuery()->getResult();
    }
}