app:
    resource: '@AppBundle/Controller/'
    type: annotation

#### IMPORTS ####
agp_registration:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

agp_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

agp_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

agp_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profil

agp_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

#### CUSTOM ROUTES ####
agp_index:
    path: /
    defaults: { _controller: AppBundle:App:index }

agp_dashboard:
    path: /dashboard/
    defaults: { _controller: AppBundle:Admin:index }

agp_trombinoscope:
    path: /trombinoscope
    defaults: { _controller: AppBundle:Admin:trombinoscope }

agp_chartre:
    path: /chartre
    defaults: { _controller: AppBundle:App:chartre }

agp_global_parameters:
    path: /params
    defaults: { _controller: AppBundle:Admin:globalParameters }

## Article ##
agp_show_article:
    path: /article/show/{slug}
    defaults: { _controller: AppBundle:Article:showArticle }

agp_list_articles:
    path: /articles/list
    defaults: { _controller: AppBundle:Article:listArticles }

agp_new_article:
    path: /article/new
    defaults: { _controller: AppBundle:Article:newArticle }

agp_edit_article:
    path: /article/{id}/edit
    defaults: { _controller: AppBundle:Article:editArticle }

agp_edit_article_image:
    path: /{id}/editArticleImage
    defaults: { _controller: AppBundle:Article:editArticleImage }

## User ##
agp_list_users:
    path: /users/list
    defaults: { _controller: AppBundle:User:listUsers }

agp_show_profile:
    path: /profil
    defaults: { _controller: AppBundle:User:showProfile }

agp_edit_profile:
    path: /profil/edit
    defaults: { _controller: AppBundle:User:editProfile }

agp_show_user:
    path: /user/{id}
    defaults: { _controller: AppBundle:User:showUser }

agp_edit_user:
    path: /user/{id}/edit
    defaults: { _controller: AppBundle:User:editUser }

agp_edit_user_image:
    path: /{id}/editUserImage
    defaults: { _controller: AppBundle:User:editUserImage }

agp_deactivate_user:
    path: /user/{id}/deactivate
    defaults: { _controller: AppBundle:User:deactivateUser }

agp_activate_user:
    path: /user/{id}/activate
    defaults: { _controller: AppBundle:User:activateUser }

agp_new_children:
    path: /user/{parentId}/children/new
    defaults: { _controller: AppBundle:User:newChildren }

## Dossier ##
agp_new_dossier:
    path: /profil/dossier/new
    defaults: { _controller: AppBundle:Dossier:newDossier }

agp_show_dossier:
    path: /user/{id}/dossier/{dossierId}/show
    defaults: { _controller: AppBundle:Dossier:showDossier }

agp_edit_dossier:
    path: /user/{id}/dossier/{dossierId}/edit
    defaults: { _controller: AppBundle:Dossier:editDossier }

agp_edit_medical_certificate:
    path: /medical-certificate/create
    defaults: { _controller: AppBundle:Dossier:editMedicalCertificate }

agp_edit_civil_certificate:
    path: /civil-certificate/create
    defaults: { _controller: AppBundle:Dossier:editCivilCertificate }

agp_list_dossiers:
    path: /dossiers/list
    defaults: { _controller: AppBundle:Dossier:listDossiers }

agp_deactivate_dossier:
    path: /user/{id}/dossier/{dossierId}/deactivate
    defaults: { _controller: AppBundle:Dossier:deactivateDossier }

agp_reject_dossier:
    path: /user/{id}/dossier/{dossierId}/reject
    defaults: { _controller: AppBundle:Dossier:rejectDossier }

agp_activate_dossier:
    path: /user/{id}/dossier/{dossierId}/activate
    defaults: { _controller: AppBundle:Dossier:activateDossier }

agp_activate_dossier_fpk:
    path: /user/{id}/dossier/{dossierId}/activate-fpk
    defaults: { _controller: AppBundle:Dossier:activateDossierFPK }

## Training ##
agp_new_training_ref:
    path: /training-ref/new
    defaults: { _controller: AppBundle:Training:newTrainingType }

agp_new_training_location:
    path: /training-location/new
    defaults: { _controller: AppBundle:Training:newTrainingLocation }

agp_new_training:
    path: /training/new
    defaults: { _controller: AppBundle:Training:newTraining }

agp_list_trainings:
    path: /trainings/list
    defaults: { _controller: AppBundle:Training:listTrainings }

agp_edit_training:
    path: /training/{id}/edit
    defaults: { _controller: AppBundle:Training:editTraining }

agp_calculate_age:
    path: /calculate-age
    defaults: { _controller: AppBundle:Dossier:calculateAge }

## Initiation ##

agp_new_initiation:
    path: /initiation/new
    defaults: { _controller: AppBundle:Initiation:newInitiation }

agp_list_initiations:
    path: /initiations/list
    defaults: { _controller: AppBundle:Initiation:listInitiations }

agp_edit_initiation:
    path: /initiation/{uniqueId}/edit
    defaults: { _controller: AppBundle:Initiation:editInitiation }