app:
    resource: '@AppBundle/Controller/'
    type: annotation

#### IMPORTS ####
agp_registration:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

agp_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

agp_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

agp_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profil

#### CUSTOM ROUTES ####
agp_index:
    path: /
    defaults: { _controller: AppBundle:App:index }

agp_dashboard:
    path: /dashboard/
    defaults: { _controller: AppBundle:Admin:index }

agp_trombinoscope:
    path: /trombinoscope
    defaults: { _controller: AppBundle:Admin:trombinoscope }

agp_global_parameters:
    path: /params
    defaults: { _controller: AppBundle:Admin:globalParameters }

agp_login:
    path: /login
    defaults: { _controller: AppBundle:App:login }

agp_news:
    path: /news
    defaults: { _controller: AppBundle:App:news }

## Article ##
agp_show_article:
    path: /article/{slug}/show
    defaults: { _controller: AppBundle:Article:showArticle }

agp_list_articles:
    path: /articles/list
    defaults: { _controller: AppBundle:Article:listArticles }

agp_new_article:
    path: /article/new
    defaults: { _controller: AppBundle:Article:newArticle }

agp_edit_article:
    path: /article/{id}/edit
    defaults: { _controller: AppBundle:Article:editArticle }

agp_edit_article_image:
    path: /{id}/editArticleImage
    defaults: { _controller: AppBundle:Article:editArticleImage }

agp_delete_article:
    path: /article/{id}/delete
    defaults: { _controller: AppBundle:Article:deleteArticle }

## Page ##
agp_show_page:
    path: /page/{slug}/show
    defaults: { _controller: AppBundle:Page:showPage }

agp_list_pages:
    path: /pages/list
    defaults: { _controller: AppBundle:Page:listPages }

agp_new_page:
    path: /page/new
    defaults: { _controller: AppBundle:Page:newPage }

agp_edit_page:
    path: /page/{id}/edit
    defaults: { _controller: AppBundle:Page:editPage }

agp_edit_page_image:
    path: /{id}/editPageImage
    defaults: { _controller: AppBundle:Page:editPageImage }

agp_delete_page:
    path: /page/{id}/delete
    defaults: { _controller: AppBundle:Page:deletePage }

## User ##
agp_list_users:
    path: /users/list
    defaults: { _controller: AppBundle:User:listUsers }

agp_show_profile:
    path: /profil
    defaults: { _controller: AppBundle:User:showProfile }

agp_edit_profile:
    path: /profil/edit
    defaults: { _controller: AppBundle:User:editProfile }

agp_show_user:
    path: /user/{id}
    defaults: { _controller: AppBundle:User:showUser }

agp_edit_user:
    path: /user/{id}/edit
    defaults: { _controller: AppBundle:User:editUser }

agp_edit_user_image:
    path: /{id}/editUserImage
    defaults: { _controller: AppBundle:User:editUserImage }

agp_deactivate_user:
    path: /user/{id}/deactivate
    defaults: { _controller: AppBundle:User:deactivateUser }

agp_activate_user:
    path: /user/{id}/activate
    defaults: { _controller: AppBundle:User:activateUser }

agp_new_children:
    path: /user/{parentId}/children/new
    defaults: { _controller: AppBundle:User:newChildren }

## Dossier ##
agp_new_dossier:
    path: /profil/dossier/new
    defaults: { _controller: AppBundle:Dossier:newDossier }

agp_show_dossier:
    path: /user/{id}/dossier/{dossierId}/show
    defaults: { _controller: AppBundle:Dossier:showDossier }

agp_edit_dossier:
    path: /user/{id}/dossier/{dossierId}/edit
    defaults: { _controller: AppBundle:Dossier:editDossier }

agp_edit_medical_certificate:
    path: /medical-certificate/create
    defaults: { _controller: AppBundle:Dossier:editMedicalCertificate }

agp_edit_civil_certificate:
    path: /civil-certificate/create
    defaults: { _controller: AppBundle:Dossier:editCivilCertificate }

agp_list_dossiers:
    path: /dossiers/list
    defaults: { _controller: AppBundle:Dossier:listDossiers }

agp_deactivate_dossier:
    path: /user/{id}/dossier/{dossierId}/deactivate
    defaults: { _controller: AppBundle:Dossier:deactivateDossier }

agp_reject_dossier:
    path: /user/{id}/dossier/{dossierId}/reject
    defaults: { _controller: AppBundle:Dossier:rejectDossier }

agp_activate_dossier:
    path: /user/{id}/dossier/{dossierId}/activate
    defaults: { _controller: AppBundle:Dossier:activateDossier }

agp_delete_dossier:
    path: /dossier/{dossierId}/delete
    defaults: { _controller: AppBundle:Dossier:deleteDossier }

agp_calculate_age:
    path: /calculate-age
    defaults: { _controller: AppBundle:Dossier:calculateAge }

agp_add_fpk_registered:
    path: /fpk-add-registered/{id}
    defaults: { _controller: AppBundle:Dossier:fpkAddRegistered }

agp_remove_fpk_registered:
    path: /fpk-remove-registered/{id}
    defaults: { _controller: AppBundle:Dossier:fpkRemoveRegistered }

## Training ##
agp_new_training_ref:
    path: /training-ref/new
    defaults: { _controller: AppBundle:Training:newTrainingType }

agp_new_training_location:
    path: /training-location/new
    defaults: { _controller: AppBundle:Training:newTrainingLocation }

agp_new_training:
    path: /training/new
    defaults: { _controller: AppBundle:Training:newTraining }

agp_list_trainings:
    path: /trainings/list
    defaults: { _controller: AppBundle:Training:listTrainings }

agp_list_trainings_ref:
    path: /trainingsRef/list
    defaults: { _controller: AppBundle:Training:listTrainingRef }

agp_list_trainings_loc:
    path: /trainingsLoc/list
    defaults: { _controller: AppBundle:Training:listTrainingLoc }

agp_edit_training:
    path: /training/{id}/edit
    defaults: { _controller: AppBundle:Training:editTraining }

agp_edit_training_loc:
    path: /trainingLoc/{id}/edit
    defaults: { _controller: AppBundle:Training:editTrainingLoc }

agp_edit_training_ref:
    path: /trainingRef/{id}/edit
    defaults: { _controller: AppBundle:Training:editTrainingRef }

agp_delete_training:
    path: /training/{id}/delete
    defaults: { _controller: AppBundle:Training:deleteTraining }

## Initiation ##
agp_new_initiation:
    path: /initiation/new
    defaults: { _controller: AppBundle:Initiation:newInitiation }

agp_list_initiations:
    path: /initiations/list
    defaults: { _controller: AppBundle:Initiation:listInitiations }

agp_edit_initiation:
    path: /initiation/{uniqueId}/edit
    defaults: { _controller: AppBundle:Initiation:editInitiation }

agp_delete_initiation:
    path: /initiation/{uniqueId}/delete
    defaults: { _controller: AppBundle:Initiation:deleteInitiation }

## Groups ##
agp_new_group:
    path: /group/new
    defaults: { _controller: AppBundle:Group:addGroup }

agp_edit_group:
    path: /group/{id}/edit
    defaults: { _controller: AppBundle:Group:editGroup }

agp_list_groups:
    path: /group/list
    defaults: { _controller: AppBundle:Group:listGroups }

agp_delete_group:
    path: /group/{id}/delete
    defaults: { _controller: AppBundle:Group:deleteGroup }