security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_SUPER_ADMIN:     ROLE_ADMIN
        ROLE_ADMIN:           ROLE_PRESIDENT
        ROLE_PRESIDENT:       ROLE_MEMBRE_CA
        ROLE_MEMBRE_CA:       ROLE_ENCADRANT
        ROLE_ENCADRANT:       ROLE_AIDE_ENCADRANT
        ROLE_AIDE_ENCADRANT:  ROLE_MEMBRE
        ROLE_MEMBRE:          ROLE_USER


    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/dashboard/, role: ROLE_USER }